fix TypeError: load() missing 1 required positional argument: 'Loader'
yaml.load() was deprecated in PyYAML 5.1, cf.
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation .